# Generated by Django 5.0.2 on 2024-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extra_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('Mealtime', models.CharField(default='Breakfast', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MealReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
            ],
        ),
    ]
