# Generated by Django 5.0.2 on 2024-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_extraitem_breakdownchart_breakdownchartextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownchart',
            name='base_meal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
