# Generated by Django 5.0.2 on 2024-03-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extra_booking',
        ),
        migrations.DeleteModel(
            name='MealReservation',
        ),
    ]
