# Generated by Django 5.0.3 on 2024-03-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
    ]
