# Generated by Django 5.0.3 on 2024-03-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_rollno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('username',)},
        ),
    ]
