# Generated by Django 5.0.3 on 2024-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_extraitem_date_extraitem_day_extraitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraitem',
            name='Type',
            field=models.TextField(default='Regular', max_length=15),
        ),
    ]
