# Generated by Django 5.0.2 on 2024-03-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mess_manager', '0002_manager_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manager',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='groups',
            field=models.ManyToManyField(related_name='manager_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_permissions',
            field=models.ManyToManyField(related_name='manager_permissions', to='auth.permission'),
        ),
    ]
