# Generated by Django 5.0.3 on 2024-03-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_manager', '0003_alter_manager_managers_manager_is_manager_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraMealMenu',
        ),
    ]
